
OrdererOrgs:
 
  - Name: Orderer
    Domain: iot-fabric.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - localhost



PeerOrgs:
#Org1 crypto
  - Name: Org1
    Domain: org1.iot-fabric.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - localhost
    
    Users:
      Count: 1

#Org2 crypto
  - Name: Org2
    Domain: org2.iot-fabric.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - localhost
    
    Users:
      Count: 1

#Org3 crypto
  - Name: Org3
    Domain: org3.iot-fabric.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - localhost
      
    Users:
      Count: 1           

